// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import LottieReact from "lottie-react";
import * as JsxRuntime from "react/jsx-runtime";
import * as ThyroidNetworkJson from "../../../src/assets/Thyroid-Network.json";

var animation = ThyroidNetworkJson;

function App(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(JsxRuntime.jsx(LottieReact, {
                        animationData: animation
                      }))
            });
}

var make = App;

export {
  animation ,
  make ,
}
/* animation Not a pure module */
